language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
install: yarn install
before_script: yarn run build
script: yarn run test
after_success:
  - yarn run travis-deploy-once "yarn run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
